services:
  randomizer:
    container_name: randomizer-backend
    build:
      context: backend
      dockerfile: DockerfileLocal
    image:
      bdettmer/token-randomizer:latest
    ports:
      - "5003:5000"
