services:
  randomizer:
    container_name: randomizer-backend
    build:
      context: backend
      dockerfile: DockerfileLocal
    image:
      bdettmer/token-randomizer:latest
    volumes:
      - ./debug:/token-randomizer/backend/out_bg
    ports:
      - "5003:5000"
