name: Deploy Backend

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'

  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:backend"
          push: true
          tags: ${{ vars.DOCKERHUB_IMAGE }}
          platforms: linux/amd64
          cache-from: type=registry,ref=bdettmer/token-randomizer:buildcache
          cache-to: type=registry,ref=bdettmer/token-randomizer:buildcache,mode=max
      - name: Deploy image
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.SERVER_HOST }}
          username: ${{vars.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ vars.SERVER_PORT }}
          script: |
            sudo docker pull ${{ vars.DOCKERHUB_IMAGE }}
            sudo docker stop randomizer-backend
            sudo docker rm randomizer-backend
            docker image prune -a --force
            sudo docker run -d --restart on-failure --name=randomizer-backend --platform linux/amd64 -p 5003:5000 ${{ vars.DOCKERHUB_IMAGE }}
